// This file was auto-generated by Fern from our API Definition.

/** Speech model variant to use for synthesis. */
export const SpeechModel = {
    Auto: "auto",
    MarsPro: "mars-pro",
    MarsFlash: "mars-flash",
    MarsInstruct: "mars-instruct",
    Mars8: "mars-8",
    Mars8Flash: "mars-8-flash",
    Mars8Instruct: "mars-8-instruct",
    Mars7: "mars-7",
    Mars6: "mars-6",
} as const;
export type SpeechModel = (typeof SpeechModel)[keyof typeof SpeechModel];
