// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         source_language: 1,
 *         media_url: "https://example.com/audio.mp3",
 *         target_languages: [1]
 *     }
 */
export interface BodyCreateSubtitleSubPost {
    source_language: CambApi.Languages | string;
    media_url: string;
    target_languages: (CambApi.Languages | string)[];
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    transcription_mode?: "fast" | "slow" | null;
    formatting_options?: CambApi.SubtitleFormattingOptions | null;
}
