// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         text: "foo",
 *         language: "ar-kw",
 *         voice_id: 1
 *     }
 */
export interface CreateStreamTtsRequestPayload {
    text: string;
    language: CambApi.TtsLanguage;
    voice_id: number;
    speech_model?: CambApi.SpeechModel;
    user_instructions?: string | null;
    enhance_named_entities_pronunciation?: boolean;
    output_configuration?: CambApi.StreamTtsOutputConfiguration;
    voice_settings?: CambApi.StreamTtsVoiceSettings;
    inference_options?: CambApi.StreamTtsInferenceOptions;
}
