// This file was auto-generated by Fern from our API Definition.

import type * as CambApi from "../../../../index.js";

/**
 * @example
 *     {
 *         video_url: "video_url",
 *         source_language: 1
 *     }
 */
export interface EndToEndDubbingRequestPayload {
    run_id?: number | null;
    project_name?: string | null;
    project_description?: string | null;
    folder_id?: number | null;
    video_url: string;
    source_language: CambApi.Languages | string;
    target_language?: CambApi.Languages | string | null;
    target_languages?: (CambApi.Languages | string)[] | null;
    selected_audio_tracks?: number[] | null;
    add_output_as_an_audio_track?: boolean | null;
    chosen_dictionaries?: number[] | null;
    ai_optimization?: boolean | null;
    /** Transcription mode: `fast` (default) or `slow` for a more thorough pass. */
    transcription_mode?: "fast" | "slow" | null;
    /** Original-language SRT contents. Parsing and size limits are validated by the API. */
    source_transcript?: CambApi.DubSRTInput | null;
    /** Translated SRT contents, at most one per requested target language. */
    target_transcripts?: CambApi.DubTargetSRTInput[] | null;
}
